-- Author: Hung Vu
DROP TABLE IF EXISTS JOBS;
CREATE TABLE JOBS (
    JOB_TITLE                   VARCHAR(128)                    NOT NULL    PRIMARY KEY,
    REQUIRED_QUALIFICATION      VARCHAR(128)                    NOT NULL,
    EXPECTED_SALARY             INTEGER             DEFAULT 0   NOT NULL,
    CONSTRAINT JOBS_VAL CHECK(REQUIRED_QUALIFICATION IN ('None', 'High School Diploma', 'Bachelor''s Degree', 'Master Degree', 'PhD' )),
    CONSTRAINT EXPECTED_SALARY_VAL CHECK(EXPECTED_SALARY >= 0)
);

DROP TABLE IF EXISTS CAREERS;
CREATE TABLE CAREERS(
    FIELD       VARCHAR(128)    DEFAULT 'STEM'      NOT NULL,
    INDUSTRY    VARCHAR(128)                        NOT NULL,
    JOB_TITLE   VARCHAR(128)                        NOT NULL,
    PRIMARY KEY (FIELD, INDUSTRY),
    CONSTRAINT FIELD_VAL CHECK(FIELD IN ('STEM', 'Science', 'Technology', 'Engineering', 'Mathematics')),
    CONSTRAINT CAREERS_FKEY FOREIGN KEY(JOB_TITLE) REFERENCES JOBS(JOB_TITLE) ON DELETE CASCADE    
);

DROP TABLE IF EXISTS EMPLOYERS;
CREATE TABLE EMPLOYERS (
    COMPANY     VARCHAR(128)                    NOT NULL        PRIMARY KEY,   
    AVG_SAL     INTEGER                         NOT NULL,
    NUM_EMP     INTEGER         DEFAULT 1       NOT NULL,
    CONSTRAINT AVG_SAL_VAL CHECK(AVG_SAL >= 0),
    CONSTRAINT NUM_EMP_VAL CHECK(NUM_EMP > 0)
);

DROP TABLE IF EXISTS LISTINGS;
CREATE TABLE LISTINGS (
    JOB_ID          SERIAL                              NOT NULL        PRIMARY KEY,
    JOB_TITLE       VARCHAR(128)                        NOT NULL,
    COMPANY         VARCHAR(128)                        NOT NULL,
    JOB_OPENINGS    INTEGER             DEFAULT 1       NOT NULL,
    PROP_SALARY     INTEGER             DEFAULT 0       NOT NULL,
    JOB_TYPE        VARCHAR(128)                        NOT NULL,
    WORK_CITY       VARCHAR(128)                        NOT NULL,
    WORK_STATE      VARCHAR(128)                        NOT NULL,
    CONSTRAINT JOB_OPENINGS_VAL CHECK(JOB_OPENINGS > 0),
    CONSTRAINT PROP_SALARY_VAL CHECK(PROP_SALARY >= 0),
    CONSTRAINT JOB_TYPE_VAL CHECK(JOB_TYPE IN ('Part-time', 'Full-time')),
    CONSTRAINT LISTINGS_FKEY_1 FOREIGN KEY(JOB_TITLE) REFERENCES JOBS(JOB_TITLE) ON DELETE CASCADE,
    CONSTRAINT LISTINGS_FKEY_2 FOREIGN KEY(COMPANY) REFERENCES EMPLOYERS(COMPANY) ON DELETE CASCADE
);